### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by jmattheis** [lotteryjs/ten-minutes-api#1]
Hey, I've seen that this project is using code from https://github.com/gotify/server this is perfectly fine but as described in the [license](https://github.com/gotify/server/blob/master/LICENSE) you are required to include this copyright notice in your project.

The license file should probably prepended to every file that was copied.

What indicates that this project uses source code from gotify/server is this c&p error which still references `"/etc/gotify/config.yml"`.

https://github.com/lotteryjs/ten-minutes-api/blob/a74ea287e52023b1c3def76675e0439ea35b4237/config/config.go#L23

**Comment by Kirk-Wang** [comment]
emmmmm……，sorry

**Comment by Kirk-Wang** [comment]
@jmattheis Updated. 🤝

**Comment by jmattheis** [comment]
Thanks! 

You don't have to include 
> The Gotify logo is licensed under the Creative Commons Attribution 4.0 International Public License.
http://creativecommons.org/licenses/by/4.0/

because you are not using the logo.
